import Head from "next/head";
import { attributes, react as HomeContent } from "@content/home.md";
import styles from "@/styles/Home.module.scss";
import Layout from "@/components/layout";
import Hero from "@/components/hero/Hero";
import Announcement from "@/components/announcement/Announcement";
import Update from "@/components/update/Update";
// import Update from "@/components/update/Update";

export default function Home() {
  let { title, heading, subheading, image, alt, buttonURL } = attributes;
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero
          heading={heading}
          image={image}
          alt={alt}
          subheading={subheading}
          link={buttonURL}
        />
        <HomeContent />
        <Update />
        <Announcement />
      </main>
    </Layout>
  );
}
