import Head from "next/head";
import { Anton, Noto_Sans } from "@next/font/google";
import { attributes, react as HomeContent } from "../../content/home.md";
import styles from "@/styles/Home.module.scss";
import Layout from "@/components/layout";
import Hero from "@/components/hero/Hero";
import Annoucement from "@/components/announcement/Announcement";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
});

const noto_sans = Noto_Sans({
  weight: "300",
  subsets: ["latin"],
});

export default function Home() {
  let { title, heading, subheading, image, alt } = attributes;
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero heading={heading} image={image} alt={alt} subheading={subheading} />
        <HomeContent />
        <Annoucement />
      </main>
    </Layout>
  );
}
