import Head from "next/head";
import Image from "next/image";
import { Anton, Noto_Sans } from "@next/font/google";
import { attributes, react as HomeContent } from "../content/home.md";
import styles from "@/styles/Home.module.scss";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
});

const noto_sans = Noto_Sans({
  weight: "300",
  subsets: ["latin"],
});

export default function Home() {
  let { title } = attributes;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <HomeContent />
      </main>
    </>
  );
}
