backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - label: "Components"
    name: "components"
    folder: "content/components"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sub-Heading",
          name: "subheading",
          widget: "string",
          required: false,
        }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Button", name: "button", widget: "string", required: false }
      - {
          label: "ButtonURL",
          name: "buttonurl",
          widget: "string",
          required: false,
        }
      - { label: "Text", name: "text", widget: "markdown", required: false }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Publish Date",
              name: "date",
              widget: "datetime",
              required: false,
            }
          - { label: "Main Heading", name: "heading", widget: "string" }
          - {
              label: "Sub-Heading",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - {
              label: "Cover Image",
              name: "image",
              widget: "image",
              required: false,
            }
          - {
              label: "Alt Text",
              name: "alt",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Audio", name: "audio-file", widget: "file", required: false }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
